# Generated by Django 5.2.12 on 2026-04-25 07:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("songs", "0002_invitation_created_at_sharelink_created_at_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="song",
            name="audio_url",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="song",
            name="duration",
            field=models.IntegerField(
                blank=True, help_text="Duration in seconds", null=True
            ),
        ),
    ]
