# Generated by Django 5.2.12 on 2026-04-25 07:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("albums", "0002_alter_album_release_date"),
        ("songs", "0003_song_audio_url_alter_song_duration"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="song",
            name="album",
        ),
        migrations.AddField(
            model_name="song",
            name="albums",
            field=models.ManyToManyField(
                blank=True, related_name="songs", to="albums.album"
            ),
        ),
        migrations.AlterField(
            model_name="song",
            name="duration",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
