# Generated by Django 5.2.12 on 2026-04-22 08:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("generation", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="generationjob",
            name="audio_urls",
            field=models.JSONField(blank=True, default=list),
        ),
    ]
