# Generated by Django 5.2.12 on 2026-04-21 06:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("quota", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="quota",
            name="used_this_week",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="quota",
            name="weekly_limit",
            field=models.IntegerField(default=10),
        ),
    ]
