# Generated by Django 5.2.12 on 2026-03-24 02:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("albums", "0001_initial"),
        ("songs", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="song",
            name="generation_status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("generating", "Generating"),
                    ("ready", "Ready"),
                    ("failed", "Failed"),
                ],
                default="pending",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="song",
            name="genre",
            field=models.CharField(
                choices=[
                    ("pop", "Pop"),
                    ("rock", "Rock"),
                    ("r&b", "R&B"),
                    ("jazz", "Jazz"),
                    ("classical", "Classical"),
                ],
                default="pop",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="song",
            name="mood",
            field=models.CharField(
                choices=[
                    ("happy", "Happy"),
                    ("sad", "Sad"),
                    ("relaxed", "Relaxed"),
                    ("energetic", "Energetic"),
                    ("chill", "Chill"),
                ],
                default="happy",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="song",
            name="occasion",
            field=models.CharField(
                choices=[
                    ("study", "Study"),
                    ("party", "Party"),
                    ("sleep", "Sleep"),
                    ("workout", "Workout"),
                ],
                default="study",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="song",
            name="privacy_status",
            field=models.CharField(
                choices=[
                    ("private", "Private"),
                    ("public", "Public"),
                    ("shared", "Shared"),
                ],
                default="private",
                max_length=20,
            ),
        ),
        migrations.CreateModel(
            name="ShareLink",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("url", models.URLField()),
                ("expires_at", models.DateTimeField()),
                ("is_active", models.BooleanField(default=True)),
                (
                    "album",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="albums.album",
                    ),
                ),
                (
                    "song",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="songs.song",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Invitation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("email", models.EmailField(max_length=254)),
                ("status", models.CharField(default="pending", max_length=20)),
                (
                    "share_link",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="invitations",
                        to="songs.sharelink",
                    ),
                ),
            ],
        ),
    ]
