# Generated by Django 5.2.12 on 2026-04-25 07:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("albums", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="album",
            name="release_date",
            field=models.DateField(blank=True, null=True),
        ),
    ]
