# Generated by Django 5.2.12 on 2026-04-25 08:21

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("albums", "0002_alter_album_release_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="album",
            name="cover_image",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="album",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="album",
            name="share_token",
            field=models.CharField(blank=True, max_length=64, null=True, unique=True),
        ),
    ]
